"""add wellness fields to student_metrics

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-09 03:09:38.053266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sleep_quality', sa.Float(), server_default='7.0', nullable=False))
        batch_op.add_column(sa.Column('screen_time', sa.Float(), server_default='8.0', nullable=False))
        batch_op.add_column(sa.Column('social_interaction', sa.Float(), server_default='5.0', nullable=False))
        batch_op.add_column(sa.Column('break_frequency', sa.Float(), server_default='5.0', nullable=False))
        batch_op.add_column(sa.Column('mood_score', sa.Float(), server_default='3.0', nullable=False))
        batch_op.add_column(sa.Column('stress_level', sa.Float(), server_default='3.0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_metrics', schema=None) as batch_op:
        batch_op.drop_column('stress_level')
        batch_op.drop_column('mood_score')
        batch_op.drop_column('break_frequency')
        batch_op.drop_column('social_interaction')
        batch_op.drop_column('screen_time')
        batch_op.drop_column('sleep_quality')

    # ### end Alembic commands ###
